Наработки для маркированной трассы со штрафными кругами
sportorg/pysport pull request #421
Opened 2023-11-15 14:19 UTC by alex-karpov

Мои наработки для маркировки со штрафными кругами (на пункте оценки печатается штраф, спортсмен проезжает требуемое количество штрафных кругов, отмечаясь на станции, может быть дисквалифицирован если проехал меньше, чем надо). Работу над проверкой маркировки параллельно вёл @sergeikobelev и его изменения попали в master. Соответственно, часть моих изменений перестали быть актуальными.

* `Настройки хронометража` -> `Штраф`. Переключение настроек в активное / не активное состояние в зависимости от выбранных настроек
* `Настройки хронометража` -> `Штраф`. Добавлены всплывающие подсказки (ToolTip) к некоторым настройкам
* Добавлен `ResultStatus.MISS_PENALTY_LAP` (пп4.6.12.7 # не прошел назначенное число штрафных кругов)
* `check_penalty_laps()` — проверка количества штрафных кругов. Сравнивает штраф на маркировке и количество отметок в штрафной станции
* `detach_penalty_laps()`, `detach_penalty_laps2()` — разделение сплита на два массива: отметки на дистанции и отметки на станции на штрафном круге
* Схема {`checking()` -> `calculate_penalty()` -> `checking()`} в нескольких местах: после первой проверки в сплит участника записываются отметки правильно / неправильно, по которым начисляется штраф; во второй проверке проверяется количество пройденных штрафных кругов
* Печать штрафа на пункте оценки (номер / штраф) через `win32print`
* `2_marked_route_penalty_A5.html` — шаблон для печати штрафа на пункте оценки (номер / штраф) для термоленты 80мм
* `3_marked_route_penalty_80mm.html` — шаблон для печати штрафа на пункте оценки (номер / штраф) на бумаге A5 (лазерный принтер)
* В шаблон для печати сплитов `1_split_printout.html` добавлена печать штрафного времени и штрафных кругов.
* `test_penalty_checking.py` — тесты для начисления штрафа
* Существующие функции для начисления штрафа (`penalty_calculation()` и `penalty_calculation_free_order()`) не менял.

Тестами охвачена проверка штрафа на дистанции. Постарался рассмотреть как можно больше разных случаев. Сомнительные (с моей точки зрения) моменты выделил в test_non_obvious_behavior(). До тестов на проверку количества штрафных кругов не добрался. Для удобства отладки, к тестам добавил информационные сообщения на случай провала: вывод сплитов и курсов, сколько штрафа ожидается и сколько начислено.

## Изменения Сергея Кобелева

Разработка велась в ветке `work`, параллельно с другими изменениями. Изменения влиты в `master` 13 июля.  Пробую перечислить отдельные коммиты. 

### Modification of courses for marked route (Russian event type with deсision points)
[7 марта](https://github.com/sportorg/pysport/commit/fb5294fdcf5a75fe9f0f7ce2b530d9499f1a6020)

Добавлено диалоговое окно Подготовка к старту -> Изменение дистанций для маркировки — для создания курсов маркировки: `31` -> `31(31,131)`

### Check penalty legs visiting
[7 марта](https://github.com/sportorg/pysport/commit/26a396e03321478a02b486ef905301e6d4ff466c), branch [marked_route_lap_control](https://github.com/sportorg/pysport/tree/marked_route_lap_control)

Добавлена функция `marked_route_check_penalty_laps()`. Считает количество отметок на станции на штрафном круге и сравнивает с начисленным штрафом. Отсутствует проверка, чтобы штрафные круги обязательно были в конце дистанции. 

По всей видимости, предполагается, что за лишние отметки штраф начисляться не будет.

Смущает часть: `if mr_if_counting_lap: count_laps = -1`. Возможно, частный случай, когда отметка на штрафном круге совмещена с последним КП. Я обычно прошу, чтобы станцию отметки ставили в дальней части штрафного круга, тогда -1 не нужен.

Спортсмен снимается со статусом `ResultStatus.MISSING_PUNCH` (как и при обычной неправильной отметки на заданке) и с комментарием `п.п.4.6.12.7` (не прошел назначенное число штрафных кругов).

### Marked route reports
[10 марта](https://github.com/sportorg/pysport/commit/36ed6e40b99e1c493dd457d0ab1a5045aed9f53e), branch [marked_route_reports](https://github.com/sportorg/pysport/tree/marked_route_reports)

Добавлены шаблоны:
* `1_маркировка_с_изображением.html` и `1_сплиты_маркировка_только_штраф.html` — сплиты для маркировки
* `2_маркировка_WO.html` и `2_маркировка_номер_и_штраф.html` — распечатки для пункта оценки: номер участника и штраф.
* `9_официальный_протокол_штраф_круги_word.docx` и `9_официальный_протокол_штраф_минуты_word.docx` — шаблоны результатов для Word

### Check result before penalty calculation. Prevent negative penalty (23:59:00 for -1)
[23 марта](https://github.com/sportorg/pysport/commit/8c06393b0655e82da0ff35e14d525e7aec179f09), branch [penalty_bug](https://github.com/sportorg/pysport/tree/penalty_bug)

Проверка штрафа перенесена после проверки правильности прохождения. Штраф не может быть отрицательным.

### Disqualify people at file open / event change
[23 марта](https://github.com/sportorg/pysport/commit/24c668f290a9ddd3e78df73c3367a95f930c04a1), branch [marked_route_dsq_on_file_open](https://github.com/sportorg/pysport/tree/marked_route_dsq_on_file_open)

Проверка штрафа и снятие спортсменов за не прохождение штрафных кругов происходит при старте спорторга.

### Penalty calculation optimization on file open / import / event change
[23 марта](https://github.com/sportorg/pysport/commit/4167ea01f5e248e579de377d3f0c9098ddcc5cf4), branch [penalty_calculation_optimization](https://github.com/sportorg/pysport/tree/penalty_calculation_optimization)

Отменён предыдущий коммит, проверка штрафа происходит в другом месте.

### New mode for time penalty - add penalty for extra controls
[29 марта](https://github.com/sportorg/pysport/commit/4167ea01f5e248e579de377d3f0c9098ddcc5cf4), branch [penalty_for_extra_cp](https://github.com/sportorg/pysport/tree/penalty_for_extra_cp)

!!! ветка не влита в `master` !!!

Добавлен режим начисления штрафа за лишние КП. Не знаю, как работает, не разбирался.

Изменено диалоговое окно `Настройки хронометража` -> `Расчёт штрафа из сплитов`. При разных комбинациях настроек другие настройки пропадают. С первого взгляда выглядит неудобно. Логичнее, чтобы оставались видны, но деактивировались, в своей версии сделал таким способом. 

### Version 1.6 release. Sum places - was inaccurate copy-pasted from sum scores. Word templates - new ranking places, macro for ranking replaced with direct realisation (Jinja2 works quite instable).
[24 мая](https://github.com/sportorg/pysport/commit/114e131c0b4251bb494cc9e08e7d91f6ba4cbe57), branch [penalty_laps_printout](https://github.com/sportorg/pysport/tree/penalty_laps_printout)

Исправлена неточность при печати штрафа в распечатке через `win32print`. 

### penalty_laps_printout and some templates
[24 мая](https://github.com/sportorg/pysport/commit/37bac877eb3b26bb9737a35d95c150d9f5d89d75)

Не содержится изменений, связанных с маркировкой.

Печать штрафа и штрафных кругов в сплитах через win32print. Ветка интегрирована в master. 

Эти ветки влиты в master, можно удалять: `marked_route_dsq_on_file_open`, `penalty_calculation_optimization`, `penalty_bug`, `marked_route_reports`, `marked_route_lap_control`. Эта ветка ещё не влита в master: `penalty_for_extra_cp`

2023-11-17 21:02 UTC, sergeikobelev commented on sportorg/models/result/result_checker.py
> +        # может дать 0 штрафа при мусоре в чипе
На практике мусор в чипе даст штраф в следующей проверке, участник с неочищенным чипом почти никогда не получит преимущество. Только если срежет и при этом неочищенные отметки с прошлой дистанции совпадут по порядку с тем, что он срезал, что маловероятно.

2023-11-17 21:37 UTC, sergeikobelev requested changes
В целом все супер! Проверил на разных базах, в целом все адекватно работает. Базы во вложении, вроде ничего конфиденциального в них нет.
Пара замечаний: настройки нужно починить, проверить, почему при переоткрытии базы многих снимает, остальное мелочи. 
[2023_11_17_marked_route_new.zip](https://github.com/sportorg/pysport/files/13397642/2023_11_17_marked_route_new.zip)

2023-11-17 21:37 UTC, sergeikobelev commented on sportorg/gui/dialogs/timekeeping_properties.py
> +        obj.set_setting('marked_route_penalty_lap_station_code', mr_station_code)
Если только тут поменять, то в диалоге не появится новое значение, оно читается из старого параметра.

2023-11-17 21:37 UTC, sergeikobelev commented on sportorg/gui/dialogs/timekeeping_properties.py
> +        obj.set_setting('marked_route_penalty_lap_station_code', mr_station_code)
Если только тут поменять, то в диалоге не появится новое значение, оно читается из старого параметра.

2023-11-17 21:37 UTC, sergeikobelev commented on languages/ru_RU/LC_MESSAGES/sportorg.po
> +msgstr "Пропущен штрафной круг"
Статус либо не так называется, либо не переводится

2023-11-17 21:37 UTC, sergeikobelev commented on sportorg/gui/dialogs/result_edit.py
>                  ResultChecker.checking(result)
Нужно наверное только 1 раз оставить checking. Я конечно понимаю, что так сделано, чтоб новый статус Missing penalty lap не перетирал снятие, а чтобы знать о снятии, надо проверить отметку.  
Но надо просто определиться, в какой последовательности должны эти команды выполняться, чтобы все было нормально.

2023-11-17 21:37 UTC, sergeikobelev commented on sportorg/gui/dialogs/timekeeping_properties.py
> +                and not self.mr_lap_station_check.isChecked()
В настройках если уйти с типа штрафа «штрафные круги», то оценочный круг становится неактивным и потом активным уже не становится. 
![image](https://github.com/sportorg/pysport/assets/26871250/bb82c652-80fb-40be-8497-2b10f60ef0b7)

Вот примерное решение, но я не совсем догнал, что изначально хотели сделать с этими двойными проверками статусов
![image](https://github.com/sportorg/pysport/assets/26871250/b441ccdc-931a-4059-8896-27a932a51f7e)

2023-11-17 21:37 UTC, sergeikobelev commented on sportorg/models/result/result_checker.py
> +        к пункту оценки, а не появляться из неочищенного чипа"""
Можно искать их с конца и прерываться, когда пойдут другие отметки.

2023-11-17 21:37 UTC, sergeikobelev commented on sportorg/modules/sportident/result_generation.py
>                  self._result = existing_res
Где-то выше уже писал, что по-хорошему надо 1 раз делать checking

2023-11-18 07:25 UTC, sergeikobelev commented
В общем предлагаю ResultChecker.calculate_penalty() оставить только в одном месте - внутри ResultChecker.checking().
И мою проверку кругов убрать еще, в ней всех снимает.
![image](https://github.com/sportorg/pysport/assets/26871250/005e5241-f9ba-4d8e-8e32-a29a93d01b38)

2023-11-28 10:34 UTC, sergeikobelev commented on sportorg/modules/printing/printout_split.py
> +        if not race().get_setting('marked_route_if_counting_lap', False):
Нужно, наверное, дополнительно проверять, что режим расчета штрафа = 'круги', на всех старых базах распечатки с номером-штрафом стали печататься
![image](https://github.com/sportorg/pysport/assets/26871250/0c84b008-1a4f-48f6-ae70-27dfda687241)

2023-12-10 11:58 UTC, sergeikobelev approved these changes

2023-12-10 12:08 UTC, daxartio commented on sportorg/gui/dialogs/timekeeping_properties.py
> +            + translate('when competitor reads out his card')
Лучше использовать f строки вместо оператора +

2023-12-10 12:08 UTC, daxartio commented on sportorg/gui/dialogs/timekeeping_properties.py
> +            + translate('when competitor reads out his card')
Также, кмк

```suggestion
            + translate('when a competitor reads out his card')
```

2023-12-10 12:10 UTC, daxartio commented on sportorg/libs/template/template.py
> +def plural(value, fmt=None):
это что-то зависимая от языка. Я бы исключал такие функции в главном коде, в шаблонах еще можно

2023-12-10 12:12 UTC, daxartio commented on sportorg/models/result/result_checker.py
> +        # может дать 0 штрафа при мусоре в чипе
Можем удалить этот коммент вообще?

2023-12-10 12:12 UTC, daxartio commented on sportorg/models/result/result_checker.py
> +        """Walkaround: извлекает отметки на штрафной станции.
Надо удалить коммент. Или написать на английском

2023-12-10 12:15 UTC, daxartio commented
В общем, стоит удалить ru комменты из кода и функции сделать тож независимыми от языка или сделать в названии соответствующую пометку: например plural_ru

2023-12-20 07:01 UTC, daxartio approved these changes

2023-12-20 07:04 UTC, merged